#!/bin/bash

func_get_local_version() {
    local curr_ver=$(cat "$V_PATH" | grep "VERSION=" | cut -d'=' -f2)
    echo "$curr_ver"
}
func_increment_version() {
    local curr_ver=$(func_get_local_version)
    local new_version=$(( curr_ver + 1))
    echo "VERSION=$new_version" > $V_PATH
}
func_print_settings() {
    echo "IP Address: $IP_ADDRESS"
    echo "PORT: $PORT"
    echo "SSH PRIVATE KEY PATH: $PRIVATE_KEY"
    echo "SYNCPASS VERSION: $V"
    echo "---"
    echo "SYNCPASS PATH: $C_PATH"
    echo "VERSION PATH: $V_PATH"
}

